# Generated by Django 3.2.6 on 2021-10-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0002_auto_20211012_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='description',
            field=models.TextField(default=False),
        ),
        migrations.AddField(
            model_name='journal',
            name='image',
            field=models.FileField(default=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='uploads',
            name='coverletter',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='uploads',
            name='figures',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='uploads',
            name='graphiabstract',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='uploads',
            name='manuscriptpdf',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='uploads',
            name='manuscriptword',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='uploads',
            name='supplementaryfiles',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
