# Generated by Django 3.2.6 on 2021-10-16 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0003_auto_20211015_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploads',
            name='coverletter',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='uploads',
            name='figures',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='uploads',
            name='graphiabstract',
            field=models.FileField(blank=True, null=True, upload_to='graphic_abstract/'),
        ),
        migrations.AlterField(
            model_name='uploads',
            name='manuscriptpdf',
            field=models.FileField(blank=True, null=True, upload_to='pdf/'),
        ),
        migrations.AlterField(
            model_name='uploads',
            name='manuscriptword',
            field=models.FileField(blank=True, null=True, upload_to='ms_word/'),
        ),
        migrations.AlterField(
            model_name='uploads',
            name='supplementaryfiles',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
