# Generated by Django 3.2.7 on 2021-09-20 08:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journal_app', '0003_rename_user_user_class'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_class',
            new_name='User',
        ),
    ]
