# Generated by Django 3.2.6 on 2021-10-17 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0004_auto_20211016_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploads',
            name='author',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='journal_app.coauthorlist'),
        ),
    ]
