# Generated by Django 3.2.7 on 2021-09-21 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('journal_app', '0006_auto_20210920_1150'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
