# Generated by Django 3.2.7 on 2021-10-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0006_alter_uploads_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploads',
            old_name='graphiabstract',
            new_name='graphicabstract',
        ),
        migrations.RemoveField(
            model_name='coauthors',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='manuscript',
            name='numberofcoauthors',
        ),
        migrations.RemoveField(
            model_name='uploads',
            name='date_added',
        ),
        migrations.AddField(
            model_name='coauthors',
            name='rand',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='rand',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='uploads',
            name='rand',
            field=models.IntegerField(default=True),
        ),
    ]
