# Generated by Django 3.2.7 on 2021-09-22 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0008_author_country_job_title_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='user',
        ),
    ]
