# Generated by Django 3.2.7 on 2021-10-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0008_auto_20211025_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_user',
            name='is_user_active',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
