# Generated by Django 3.2.7 on 2021-10-26 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0010_alter_my_user_is_user_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='my_user',
            name='is_user_active',
        ),
    ]
