# Generated by Django 3.2.7 on 2021-10-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0011_remove_my_user_is_user_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='publish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_year', models.IntegerField()),
                ('published_volume', models.IntegerField()),
                ('published_issue', models.IntegerField()),
                ('published_page_start', models.IntegerField()),
                ('published_page_end', models.IntegerField()),
                ('published_abstract', models.TextField(max_length=3000)),
                ('published_full_text', models.TextField(max_length=3000)),
                ('published_pdf', models.FileField(upload_to='published/')),
                ('rand', models.IntegerField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='uploads',
            name='coverletter',
        ),
        migrations.RemoveField(
            model_name='uploads',
            name='figures',
        ),
        migrations.RemoveField(
            model_name='uploads',
            name='graphicabstract',
        ),
        migrations.RemoveField(
            model_name='uploads',
            name='manuscriptpdf',
        ),
        migrations.RemoveField(
            model_name='uploads',
            name='supplementaryfiles',
        ),
        migrations.AlterField(
            model_name='uploads',
            name='manuscriptword',
            field=models.FileField(default=True, upload_to='ms_word/'),
        ),
    ]
