# Generated by Django 3.2.7 on 2021-10-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0012_auto_20211029_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='publish',
            name='published_status',
            field=models.IntegerField(default=0),
        ),
    ]
