# Generated by Django 3.2.7 on 2021-10-30 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0014_auto_20211030_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publish',
            name='published_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='publish',
            name='rand',
            field=models.IntegerField(default=True),
        ),
    ]
