# Generated by Django 3.2.7 on 2021-10-31 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0015_auto_20211030_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='published_status',
            field=models.BooleanField(default=False),
        ),
    ]
