# Generated by Django 3.2.6 on 2021-09-25 20:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journal_app', '0016_auto_20210925_2111'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Uzer',
            new_name='my_user',
        ),
    ]
