# Generated by Django 3.2.7 on 2021-11-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0016_manuscript_published_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploads',
            name='manuscriptword',
            field=models.FileField(upload_to='ms_word/'),
        ),
    ]
