# Generated by Django 3.2.7 on 2021-11-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0018_front_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='front_page',
            name='slider2',
            field=models.FileField(default=True, upload_to='frontpage/'),
        ),
        migrations.AddField(
            model_name='front_page',
            name='slider3',
            field=models.FileField(default=True, upload_to='frontpage/'),
        ),
    ]
