# Generated by Django 3.2.6 on 2021-09-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0026_my_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_user',
            name='username',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
