# Generated by Django 3.2.6 on 2021-09-27 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0027_alter_my_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='my_user',
            name='user',
        ),
    ]
