# Generated by Django 3.2.6 on 2021-09-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0028_remove_my_user_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_user',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
